-- MySQL Script generated by MySQL Workbench
-- 03/26/16 16:42:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema smdedbv1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smdedbv1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smdedbv1` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `smdedbv1` ;

-- -----------------------------------------------------
-- Table `smdedbv1`.`Institute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Institute` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Institute` (
  `idInstitute` VARCHAR(30) NOT NULL COMMENT '',
  `instituteName` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idInstitute`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`User` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`User` (
  `userEmail` VARCHAR(100) NOT NULL COMMENT '',
  `userName` VARCHAR(80) NOT NULL COMMENT '',
  `userLastName` CHAR(80) NOT NULL COMMENT '',
  `userSecondLastName` CHAR(80) NOT NULL COMMENT '',
  `userSex` CHAR(1) NOT NULL COMMENT '',
  `userPassword` VARCHAR(100) NOT NULL COMMENT '',
  `darkTheme` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `msmColor` VARCHAR(30) NULL COMMENT '',
  `Institute_idInstitute` VARCHAR(30) NOT NULL COMMENT '',
  PRIMARY KEY (`userEmail`, `Institute_idInstitute`)  COMMENT '',
  INDEX `fk_User_Institute1_idx` (`Institute_idInstitute` ASC)  COMMENT '',
  CONSTRAINT `fk_User_Institute1`
    FOREIGN KEY (`Institute_idInstitute`)
    REFERENCES `smdedbv1`.`Institute` (`idInstitute`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Course` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Course` (
  `idCourse` VARCHAR(20) NOT NULL COMMENT '',
  `courseName` VARCHAR(10) NOT NULL COMMENT '',
  `courseLevel` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idCourse`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Lobby`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Lobby` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Lobby` (
  `idLobby` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`idLobby`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Message` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Message` (
  `idMessage` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `messageText` MEDIUMTEXT NULL COMMENT '',
  `messageDateTime` DATETIME NOT NULL COMMENT '',
  `messageStatus` TINYINT(1) NOT NULL COMMENT '',
  `Lobby_idLobby` VARCHAR(20) NOT NULL COMMENT '',
  `User_userEmail` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`idMessage`, `Lobby_idLobby`, `User_userEmail`)  COMMENT '',
  INDEX `fk_Menssage_Lobby1_idx` (`Lobby_idLobby` ASC)  COMMENT '',
  INDEX `fk_Message_User1_idx` (`User_userEmail` ASC)  COMMENT '',
  CONSTRAINT `fk_Menssage_Lobby1`
    FOREIGN KEY (`Lobby_idLobby`)
    REFERENCES `smdedbv1`.`Lobby` (`idLobby`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_User1`
    FOREIGN KEY (`User_userEmail`)
    REFERENCES `smdedbv1`.`User` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Department` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Department` (
  `idDepartment` VARCHAR(20) NOT NULL COMMENT '',
  `departmentName` VARCHAR(200) NULL COMMENT '',
  `Institute_idInstitute` VARCHAR(30) NOT NULL COMMENT '',
  PRIMARY KEY (`Institute_idInstitute`, `idDepartment`)  COMMENT '',
  INDEX `fk_Department_Institute1_idx` (`Institute_idInstitute` ASC)  COMMENT '',
  CONSTRAINT `fk_Department_Institute1`
    FOREIGN KEY (`Institute_idInstitute`)
    REFERENCES `smdedbv1`.`Institute` (`idInstitute`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Teacher` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Teacher` (
  `idTeacher` VARCHAR(20) NOT NULL COMMENT '',
  `User_userEmail` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`idTeacher`, `User_userEmail`)  COMMENT '',
  INDEX `fk_Teacher_User1_idx` (`User_userEmail` ASC)  COMMENT '',
  CONSTRAINT `fk_Teacher_User1`
    FOREIGN KEY (`User_userEmail`)
    REFERENCES `smdedbv1`.`User` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Subject` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Subject` (
  `idSubject` VARCHAR(20) NOT NULL COMMENT '',
  `subjectName` VARCHAR(20) NOT NULL COMMENT '',
  `subjectLevel` INT NOT NULL COMMENT '',
  `Department_Institute_idInstitute` VARCHAR(30) NOT NULL COMMENT '',
  `Department_idDepartment` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`idSubject`, `Department_idDepartment`)  COMMENT '',
  INDEX `fk_Subject_Department1_idx` (`Department_Institute_idInstitute` ASC, `Department_idDepartment` ASC)  COMMENT '',
  CONSTRAINT `fk_Subject_Department1`
    FOREIGN KEY (`Department_Institute_idInstitute` , `Department_idDepartment`)
    REFERENCES `smdedbv1`.`Department` (`Institute_idInstitute` , `idDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Subject_has_Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Subject_has_Course` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Subject_has_Course` (
  `Subject_idSubject` VARCHAR(20) NOT NULL COMMENT '',
  `Course_idCourse` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`Subject_idSubject`, `Course_idCourse`)  COMMENT '',
  INDEX `fk_Subject_has_Course_Course1_idx` (`Course_idCourse` ASC)  COMMENT '',
  INDEX `fk_Subject_has_Course_Subject1_idx` (`Subject_idSubject` ASC)  COMMENT '',
  CONSTRAINT `fk_Subject_has_Course_Subject1`
    FOREIGN KEY (`Subject_idSubject`)
    REFERENCES `smdedbv1`.`Subject` (`idSubject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subject_has_Course_Course1`
    FOREIGN KEY (`Course_idCourse`)
    REFERENCES `smdedbv1`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Publication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Publication` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Publication` (
  `idPublication` VARCHAR(20) NOT NULL COMMENT '',
  `pubTitle` VARCHAR(100) NULL COMMENT '',
  `pubText` MEDIUMTEXT NULL COMMENT '',
  `pubDateTime` DATETIME NULL COMMENT '',
  `Teacher_User_userEmail` VARCHAR(100) NOT NULL COMMENT '',
  `Subject_has_Course_Subject_idSubject` VARCHAR(20) NOT NULL COMMENT '',
  `Subject_has_Course_Course_idCourse` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`idPublication`, `Teacher_User_userEmail`)  COMMENT '',
  INDEX `fk_Publication_Teacher1_idx` (`Teacher_User_userEmail` ASC)  COMMENT '',
  INDEX `fk_Publication_Subject_has_Course1_idx` (`Subject_has_Course_Subject_idSubject` ASC, `Subject_has_Course_Course_idCourse` ASC)  COMMENT '',
  CONSTRAINT `fk_Publication_Teacher1`
    FOREIGN KEY (`Teacher_User_userEmail`)
    REFERENCES `smdedbv1`.`Teacher` (`User_userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Publication_Subject_has_Course1`
    FOREIGN KEY (`Subject_has_Course_Subject_idSubject` , `Subject_has_Course_Course_idCourse`)
    REFERENCES `smdedbv1`.`Subject_has_Course` (`Subject_idSubject` , `Course_idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Student` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Student` (
  `idStudent` VARCHAR(20) NOT NULL COMMENT '',
  `User_userEmail` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`idStudent`, `User_userEmail`)  COMMENT '',
  INDEX `fk_Student_User1_idx` (`User_userEmail` ASC)  COMMENT '',
  CONSTRAINT `fk_Student_User1`
    FOREIGN KEY (`User_userEmail`)
    REFERENCES `smdedbv1`.`User` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Feedback` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Feedback` (
  `idFeedback` VARCHAR(20) NOT NULL COMMENT '',
  `feedTitle` VARCHAR(45) NULL COMMENT '',
  `feedText` MEDIUMTEXT NULL COMMENT '',
  `feedDateTime` DATETIME NULL COMMENT '',
  `Publication_idPublication` VARCHAR(20) NOT NULL COMMENT '',
  `Student_User_userEmail` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`idFeedback`, `Publication_idPublication`, `Student_User_userEmail`)  COMMENT '',
  INDEX `fk_Feedback_Publication1_idx` (`Publication_idPublication` ASC)  COMMENT '',
  INDEX `fk_Feedback_Student1_idx` (`Student_User_userEmail` ASC)  COMMENT '',
  CONSTRAINT `fk_Feedback_Publication1`
    FOREIGN KEY (`Publication_idPublication`)
    REFERENCES `smdedbv1`.`Publication` (`idPublication`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Feedback_Student1`
    FOREIGN KEY (`Student_User_userEmail`)
    REFERENCES `smdedbv1`.`Student` (`User_userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Content` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Content` (
  `idContent` VARCHAR(20) NOT NULL COMMENT '',
  `contentTitle` VARCHAR(45) NULL COMMENT '',
  `contentDateTime` DATETIME NULL COMMENT '',
  `contentText` MEDIUMTEXT NULL COMMENT '',
  `Teacher_User_userEmail` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`idContent`, `Teacher_User_userEmail`)  COMMENT '',
  INDEX `fk_Content_Teacher1_idx` (`Teacher_User_userEmail` ASC)  COMMENT '',
  CONSTRAINT `fk_Content_Teacher1`
    FOREIGN KEY (`Teacher_User_userEmail`)
    REFERENCES `smdedbv1`.`Teacher` (`User_userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`ForumTopic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`ForumTopic` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`ForumTopic` (
  `idForumTopic` VARCHAR(20) NOT NULL COMMENT '',
  `topicTitle` VARCHAR(100) NOT NULL COMMENT '',
  `topicSubject` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`idForumTopic`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Note` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Note` (
  `noteValue` VARCHAR(3) NULL COMMENT '',
  `noteComment` MEDIUMTEXT NULL COMMENT '',
  `Student_User_userEmail` VARCHAR(100) NOT NULL COMMENT '',
  `noteTitle` VARCHAR(200) NULL COMMENT '',
  PRIMARY KEY (`Student_User_userEmail`)  COMMENT '',
  INDEX `fk_Note_Student1_idx` (`Student_User_userEmail` ASC)  COMMENT '',
  CONSTRAINT `fk_Note_Student1`
    FOREIGN KEY (`Student_User_userEmail`)
    REFERENCES `smdedbv1`.`Student` (`User_userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Reminder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Reminder` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Reminder` (
  `idReminder` VARCHAR(20) NOT NULL COMMENT '',
  `reminderTitle` VARCHAR(100) NULL COMMENT '',
  `reminderText` MEDIUMTEXT NULL COMMENT '',
  `reminderDateTime` DATETIME NOT NULL COMMENT '',
  `User_userEmail` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`idReminder`, `User_userEmail`)  COMMENT '',
  INDEX `fk_Reminder_User1_idx` (`User_userEmail` ASC)  COMMENT '',
  CONSTRAINT `fk_Reminder_User1`
    FOREIGN KEY (`User_userEmail`)
    REFERENCES `smdedbv1`.`User` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`ForumComent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`ForumComent` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`ForumComent` (
  `idForumComent` VARCHAR(20) NOT NULL COMMENT '',
  `forumText` MEDIUMTEXT NULL COMMENT '',
  `User_userEmail` VARCHAR(100) NOT NULL COMMENT '',
  `ForumTopic_idForumTopic` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`idForumComent`, `User_userEmail`, `ForumTopic_idForumTopic`)  COMMENT '',
  INDEX `fk_ForumComent_User1_idx` (`User_userEmail` ASC)  COMMENT '',
  INDEX `fk_ForumComent_ForumTopic1_idx` (`ForumTopic_idForumTopic` ASC)  COMMENT '',
  CONSTRAINT `fk_ForumComent_User1`
    FOREIGN KEY (`User_userEmail`)
    REFERENCES `smdedbv1`.`User` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ForumComent_ForumTopic1`
    FOREIGN KEY (`ForumTopic_idForumTopic`)
    REFERENCES `smdedbv1`.`ForumTopic` (`idForumTopic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`User_has_Lobby`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`User_has_Lobby` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`User_has_Lobby` (
  `User_userEmail` VARCHAR(100) NOT NULL COMMENT '',
  `Lobby_idLobby` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`User_userEmail`, `Lobby_idLobby`)  COMMENT '',
  INDEX `fk_User_has_Lobby_Lobby1_idx` (`Lobby_idLobby` ASC)  COMMENT '',
  INDEX `fk_User_has_Lobby_User1_idx` (`User_userEmail` ASC)  COMMENT '',
  CONSTRAINT `fk_User_has_Lobby_User1`
    FOREIGN KEY (`User_userEmail`)
    REFERENCES `smdedbv1`.`User` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Lobby_Lobby1`
    FOREIGN KEY (`Lobby_idLobby`)
    REFERENCES `smdedbv1`.`Lobby` (`idLobby`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Administrator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Administrator` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Administrator` (
  `idAdministrator` VARCHAR(20) NOT NULL COMMENT '',
  `User_userEmail` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`idAdministrator`, `User_userEmail`)  COMMENT '',
  INDEX `fk_Administrator_User1_idx` (`User_userEmail` ASC)  COMMENT '',
  CONSTRAINT `fk_Administrator_User1`
    FOREIGN KEY (`User_userEmail`)
    REFERENCES `smdedbv1`.`User` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Notification` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Notification` (
  `idNotification` VARCHAR(20) NOT NULL COMMENT '',
  `notifTitle` VARCHAR(200) NOT NULL COMMENT '',
  `notifText` MEDIUMTEXT NOT NULL COMMENT '',
  `Seen` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `notifZelda` MEDIUMTEXT NULL COMMENT '',
  PRIMARY KEY (`idNotification`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`User_has_Notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`User_has_Notification` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`User_has_Notification` (
  `User_userEmail` VARCHAR(100) NOT NULL COMMENT '',
  `Notification_idNotification` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`User_userEmail`, `Notification_idNotification`)  COMMENT '',
  INDEX `fk_User_has_Notification_Notification1_idx` (`Notification_idNotification` ASC)  COMMENT '',
  INDEX `fk_User_has_Notification_User1_idx` (`User_userEmail` ASC)  COMMENT '',
  CONSTRAINT `fk_User_has_Notification_User1`
    FOREIGN KEY (`User_userEmail`)
    REFERENCES `smdedbv1`.`User` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Notification_Notification1`
    FOREIGN KEY (`Notification_idNotification`)
    REFERENCES `smdedbv1`.`Notification` (`idNotification`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Teacher_has_Subject_has_Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Teacher_has_Subject_has_Course` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Teacher_has_Subject_has_Course` (
  `Teacher_idTeacher` VARCHAR(20) NOT NULL COMMENT '',
  `Subject_has_Course_Subject_idSubject` VARCHAR(20) NOT NULL COMMENT '',
  `Subject_has_Course_Course_idCourse` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`Teacher_idTeacher`, `Subject_has_Course_Subject_idSubject`, `Subject_has_Course_Course_idCourse`)  COMMENT '',
  INDEX `fk_Teacher_has_Subject_has_Course_Subject_has_Course1_idx` (`Subject_has_Course_Subject_idSubject` ASC, `Subject_has_Course_Course_idCourse` ASC)  COMMENT '',
  INDEX `fk_Teacher_has_Subject_has_Course_Teacher1_idx` (`Teacher_idTeacher` ASC)  COMMENT '',
  CONSTRAINT `fk_Teacher_has_Subject_has_Course_Teacher1`
    FOREIGN KEY (`Teacher_idTeacher`)
    REFERENCES `smdedbv1`.`Teacher` (`idTeacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teacher_has_Subject_has_Course_Subject_has_Course1`
    FOREIGN KEY (`Subject_has_Course_Subject_idSubject` , `Subject_has_Course_Course_idCourse`)
    REFERENCES `smdedbv1`.`Subject_has_Course` (`Subject_idSubject` , `Course_idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Student_has_Subject_has_Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Student_has_Subject_has_Course` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Student_has_Subject_has_Course` (
  `Student_idStudent` VARCHAR(20) NOT NULL COMMENT '',
  `Subject_has_Course_Subject_idSubject` VARCHAR(20) NOT NULL COMMENT '',
  `Subject_has_Course_Course_idCourse` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`Student_idStudent`, `Subject_has_Course_Subject_idSubject`, `Subject_has_Course_Course_idCourse`)  COMMENT '',
  INDEX `fk_Student_has_Subject_has_Course_Subject_has_Course1_idx` (`Subject_has_Course_Subject_idSubject` ASC, `Subject_has_Course_Course_idCourse` ASC)  COMMENT '',
  INDEX `fk_Student_has_Subject_has_Course_Student1_idx` (`Student_idStudent` ASC)  COMMENT '',
  CONSTRAINT `fk_Student_has_Subject_has_Course_Student1`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `smdedbv1`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Subject_has_Course_Subject_has_Course1`
    FOREIGN KEY (`Subject_has_Course_Subject_idSubject` , `Subject_has_Course_Course_idCourse`)
    REFERENCES `smdedbv1`.`Subject_has_Course` (`Subject_idSubject` , `Course_idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `smdedbv1`.`Institute`
-- -----------------------------------------------------
START TRANSACTION;
USE `smdedbv1`;
INSERT INTO `smdedbv1`.`Institute` (`idInstitute`, `instituteName`) VALUES ('PoliV9', 'Voca 9 Batiz');

COMMIT;

