-- MySQL Script generated by MySQL Workbench
-- 07/13/16 16:10:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema smdedbv1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `smdedbv1` ;

-- -----------------------------------------------------
-- Schema smdedbv1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smdedbv1` DEFAULT CHARACTER SET utf8 ;
USE `smdedbv1` ;

-- -----------------------------------------------------
-- Table `smdedbv1`.`Institute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Institute` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Institute` (
  `idInstitute` VARCHAR(100) NOT NULL,
  `instituteName` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`idInstitute`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`User` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`User` (
  `userEmail` VARCHAR(100) NOT NULL,
  `userName` CHAR(80) NOT NULL,
  `userLastName` CHAR(80) NOT NULL,
  `userSecondLastName` CHAR(80) NOT NULL,
  `userSex` CHAR(1) NOT NULL,
  `userPassword` VARCHAR(100) NOT NULL,
  `darkTheme` TINYINT(1) NOT NULL DEFAULT 0,
  `msmColor` VARCHAR(30) NULL DEFAULT '#03A9F4',
  `Institute_idInstitute` VARCHAR(100) NOT NULL,
  `photoName` VARCHAR(40) NULL,
  PRIMARY KEY (`userEmail`),
  INDEX `fk_User_Institute1_idx` (`Institute_idInstitute` ASC),
  CONSTRAINT `fk_User_Institute1`
    FOREIGN KEY (`Institute_idInstitute`)
    REFERENCES `smdedbv1`.`Institute` (`idInstitute`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Course` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Course` (
  `idCourse` VARCHAR(40) NOT NULL,
  `courseName` VARCHAR(40) NOT NULL,
  `courseLevel` INT NOT NULL,
  `Institute_idInstitute` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idCourse`, `Institute_idInstitute`),
  INDEX `fk_Course_Institute1_idx` (`Institute_idInstitute` ASC),
  CONSTRAINT `fk_Course_Institute1`
    FOREIGN KEY (`Institute_idInstitute`)
    REFERENCES `smdedbv1`.`Institute` (`idInstitute`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Lobby`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Lobby` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Lobby` (
  `idLobby` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idLobby`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Message` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Message` (
  `idMessage` VARCHAR(150) NOT NULL,
  `messageText` MEDIUMTEXT NOT NULL,
  `messageDateTime` DATETIME NOT NULL,
  `messageStatus` TINYINT(1) NOT NULL DEFAULT 0,
  `Lobby_idLobby` VARCHAR(40) NOT NULL,
  `User_userEmail` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idMessage`, `Lobby_idLobby`, `User_userEmail`),
  INDEX `fk_Menssage_Lobby1_idx` (`Lobby_idLobby` ASC),
  INDEX `fk_Message_User1_idx` (`User_userEmail` ASC),
  CONSTRAINT `fk_Menssage_Lobby1`
    FOREIGN KEY (`Lobby_idLobby`)
    REFERENCES `smdedbv1`.`Lobby` (`idLobby`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_User1`
    FOREIGN KEY (`User_userEmail`)
    REFERENCES `smdedbv1`.`User` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Department` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Department` (
  `idDepartment` VARCHAR(100) NOT NULL,
  `departmentName` VARCHAR(200) NULL,
  `Institute_idInstitute` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`Institute_idInstitute`, `idDepartment`),
  INDEX `fk_Department_Institute1_idx` (`Institute_idInstitute` ASC),
  CONSTRAINT `fk_Department_Institute1`
    FOREIGN KEY (`Institute_idInstitute`)
    REFERENCES `smdedbv1`.`Institute` (`idInstitute`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Subject` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Subject` (
  `idSubject` VARCHAR(40) NOT NULL,
  `subjectName` VARCHAR(200) NOT NULL,
  `subjectLevel` INT NOT NULL,
  `Department_Institute_idInstitute` VARCHAR(100) NOT NULL,
  `Department_idDepartment` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idSubject`, `Department_idDepartment`, `Department_Institute_idInstitute`),
  INDEX `fk_Subject_Department1_idx` (`Department_Institute_idInstitute` ASC, `Department_idDepartment` ASC),
  CONSTRAINT `fk_Subject_Department1`
    FOREIGN KEY (`Department_Institute_idInstitute` , `Department_idDepartment`)
    REFERENCES `smdedbv1`.`Department` (`Institute_idInstitute` , `idDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Subject_has_Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Subject_has_Course` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Subject_has_Course` (
  `Subject_idSubject` VARCHAR(40) NOT NULL,
  `Course_idCourse` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`Subject_idSubject`, `Course_idCourse`),
  INDEX `fk_Subject_has_Course_Course1_idx` (`Course_idCourse` ASC),
  INDEX `fk_Subject_has_Course_Subject1_idx` (`Subject_idSubject` ASC),
  CONSTRAINT `fk_Subject_has_Course_Subject1`
    FOREIGN KEY (`Subject_idSubject`)
    REFERENCES `smdedbv1`.`Subject` (`idSubject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subject_has_Course_Course1`
    FOREIGN KEY (`Course_idCourse`)
    REFERENCES `smdedbv1`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Publication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Publication` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Publication` (
  `idPublication` VARCHAR(40) NOT NULL,
  `pubTitle` VARCHAR(100) NOT NULL,
  `pubText` MEDIUMTEXT NULL,
  `pubDateTime` DATETIME NOT NULL,
  `publicationLimitDate` DATETIME NOT NULL,
  `pubEvaluate` TINYINT(1) NOT NULL,
  `Teacher_User_userEmail` VARCHAR(100) NOT NULL,
  `Subject_has_Course_Subject_idSubject` VARCHAR(40) NOT NULL,
  `Subject_has_Course_Course_idCourse` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idPublication`, `pubTitle`, `pubDateTime`, `Teacher_User_userEmail`),
  INDEX `fk_Publication_Subject_has_Course1_idx` (`Subject_has_Course_Subject_idSubject` ASC, `Subject_has_Course_Course_idCourse` ASC),
  CONSTRAINT `fk_Publication_Subject_has_Course1`
    FOREIGN KEY (`Subject_has_Course_Subject_idSubject` , `Subject_has_Course_Course_idCourse`)
    REFERENCES `smdedbv1`.`Subject_has_Course` (`Subject_idSubject` , `Course_idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Student` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Student` (
  `idStudent` VARCHAR(40) NOT NULL,
  `User_userEmail` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idStudent`, `User_userEmail`),
  INDEX `fk_Student_User1_idx` (`User_userEmail` ASC),
  CONSTRAINT `fk_Student_User1`
    FOREIGN KEY (`User_userEmail`)
    REFERENCES `smdedbv1`.`User` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Feedback` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Feedback` (
  `idFeedback` VARCHAR(40) NOT NULL,
  `feedTitle` VARCHAR(300) NOT NULL,
  `feedText` MEDIUMTEXT NULL,
  `feedDateTime` DATETIME NOT NULL,
  `feedNote` TINYINT(2) NULL,
  `Publication_idPublication` VARCHAR(40) NOT NULL,
  `Student_User_userEmail` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idFeedback`, `Publication_idPublication`, `Student_User_userEmail`),
  INDEX `fk_Feedback_Publication1_idx` (`Publication_idPublication` ASC),
  INDEX `fk_Feedback_Student1_idx` (`Student_User_userEmail` ASC),
  CONSTRAINT `fk_Feedback_Publication1`
    FOREIGN KEY (`Publication_idPublication`)
    REFERENCES `smdedbv1`.`Publication` (`idPublication`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Feedback_Student1`
    FOREIGN KEY (`Student_User_userEmail`)
    REFERENCES `smdedbv1`.`Student` (`User_userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Teacher` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Teacher` (
  `idTeacher` VARCHAR(40) NOT NULL,
  `User_userEmail` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTeacher`, `User_userEmail`),
  INDEX `fk_Teacher_User1_idx` (`User_userEmail` ASC),
  CONSTRAINT `fk_Teacher_User1`
    FOREIGN KEY (`User_userEmail`)
    REFERENCES `smdedbv1`.`User` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Content` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Content` (
  `idContent` VARCHAR(40) NOT NULL,
  `contentTitle` VARCHAR(45) NULL,
  `contentDateTime` DATETIME NULL,
  `contentText` MEDIUMTEXT NULL,
  `Teacher_User_userEmail` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idContent`, `Teacher_User_userEmail`),
  INDEX `fk_Content_Teacher1_idx` (`Teacher_User_userEmail` ASC),
  CONSTRAINT `fk_Content_Teacher1`
    FOREIGN KEY (`Teacher_User_userEmail`)
    REFERENCES `smdedbv1`.`Teacher` (`User_userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`ForumTopic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`ForumTopic` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`ForumTopic` (
  `idForumTopic` VARCHAR(40) NOT NULL,
  `topicTitle` VARCHAR(240) NOT NULL,
  `topicSubject` VARCHAR(100) NOT NULL,
  `topicDateTime` DATETIME NOT NULL,
  `topicDescription` MEDIUMTEXT NULL,
  `User_userEmail` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idForumTopic`),
  INDEX `fk_ForumTopic_User1_idx` (`User_userEmail` ASC),
  CONSTRAINT `fk_ForumTopic_User1`
    FOREIGN KEY (`User_userEmail`)
    REFERENCES `smdedbv1`.`User` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Student_has_Subject_has_Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Student_has_Subject_has_Course` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Student_has_Subject_has_Course` (
  `Student_idStudent` VARCHAR(40) NOT NULL,
  `Subject_has_Course_Subject_idSubject` VARCHAR(40) NOT NULL,
  `Subject_has_Course_Course_idCourse` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`Student_idStudent`, `Subject_has_Course_Subject_idSubject`, `Subject_has_Course_Course_idCourse`),
  INDEX `fk_Student_has_Subject_has_Course_Subject_has_Course1_idx` (`Subject_has_Course_Subject_idSubject` ASC, `Subject_has_Course_Course_idCourse` ASC),
  INDEX `fk_Student_has_Subject_has_Course_Student1_idx` (`Student_idStudent` ASC),
  CONSTRAINT `fk_Student_has_Subject_has_Course_Student1`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `smdedbv1`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Subject_has_Course_Subject_has_Course1`
    FOREIGN KEY (`Subject_has_Course_Subject_idSubject` , `Subject_has_Course_Course_idCourse`)
    REFERENCES `smdedbv1`.`Subject_has_Course` (`Subject_idSubject` , `Course_idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Note` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Note` (
  `noteValue` TINYINT(2) NULL,
  `noteComment` MEDIUMTEXT NULL,
  `idNote` VARCHAR(100) NOT NULL,
  `Note_idStudent` VARCHAR(40) NOT NULL,
  `Note_idSubject` VARCHAR(40) NOT NULL,
  `Note_idCourse` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idNote`, `Note_idStudent`, `Note_idSubject`, `Note_idCourse`),
  INDEX `fk_Note_Student_has_Subject_has_Course1_idx` (`Note_idStudent` ASC, `Note_idSubject` ASC, `Note_idCourse` ASC),
  CONSTRAINT `fk_Note_Student_has_Subject_has_Course1`
    FOREIGN KEY (`Note_idStudent` , `Note_idSubject` , `Note_idCourse`)
    REFERENCES `smdedbv1`.`Student_has_Subject_has_Course` (`Student_idStudent` , `Subject_has_Course_Subject_idSubject` , `Subject_has_Course_Course_idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Reminder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Reminder` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Reminder` (
  `idReminder` VARCHAR(40) NOT NULL,
  `reminderTitle` VARCHAR(100) NOT NULL,
  `reminderText` MEDIUMTEXT NULL,
  `reminderDateTime` DATETIME NOT NULL,
  `User_userEmail` VARCHAR(100) NOT NULL,
  `reminderLimitDate` DATETIME NULL,
  PRIMARY KEY (`idReminder`, `User_userEmail`),
  INDEX `fk_Reminder_User1_idx` (`User_userEmail` ASC),
  CONSTRAINT `fk_Reminder_User1`
    FOREIGN KEY (`User_userEmail`)
    REFERENCES `smdedbv1`.`User` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`ForumComment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`ForumComment` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`ForumComment` (
  `idForumComment` VARCHAR(40) NOT NULL,
  `forumCommentText` MEDIUMTEXT NOT NULL,
  `forumCommentDateTime` DATETIME NOT NULL,
  `User_userEmail` VARCHAR(100) NOT NULL,
  `ForumTopic_idForumTopic` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idForumComment`, `User_userEmail`, `ForumTopic_idForumTopic`),
  INDEX `fk_ForumComent_User1_idx` (`User_userEmail` ASC),
  INDEX `fk_ForumComent_ForumTopic1_idx` (`ForumTopic_idForumTopic` ASC),
  CONSTRAINT `fk_ForumComent_User1`
    FOREIGN KEY (`User_userEmail`)
    REFERENCES `smdedbv1`.`User` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ForumComent_ForumTopic1`
    FOREIGN KEY (`ForumTopic_idForumTopic`)
    REFERENCES `smdedbv1`.`ForumTopic` (`idForumTopic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`User_has_Lobby`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`User_has_Lobby` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`User_has_Lobby` (
  `User_userEmail` VARCHAR(100) NOT NULL,
  `Lobby_idLobby` VARCHAR(40) NOT NULL,
  `lobbyStatus` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`User_userEmail`, `Lobby_idLobby`),
  INDEX `fk_User_has_Lobby_Lobby1_idx` (`Lobby_idLobby` ASC),
  INDEX `fk_User_has_Lobby_User1_idx` (`User_userEmail` ASC),
  CONSTRAINT `fk_User_has_Lobby_User1`
    FOREIGN KEY (`User_userEmail`)
    REFERENCES `smdedbv1`.`User` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Lobby_Lobby1`
    FOREIGN KEY (`Lobby_idLobby`)
    REFERENCES `smdedbv1`.`Lobby` (`idLobby`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Administrator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Administrator` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Administrator` (
  `idAdministrator` VARCHAR(40) NOT NULL,
  `User_userEmail` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idAdministrator`, `User_userEmail`),
  INDEX `fk_Administrator_User1_idx` (`User_userEmail` ASC),
  CONSTRAINT `fk_Administrator_User1`
    FOREIGN KEY (`User_userEmail`)
    REFERENCES `smdedbv1`.`User` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Notification` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Notification` (
  `idNotification` VARCHAR(40) NOT NULL,
  `notifTitle` VARCHAR(200) NOT NULL,
  `notifText` MEDIUMTEXT NOT NULL,
  `notifStatus` TINYINT(1) NOT NULL DEFAULT 0,
  `notifZelda` MEDIUMTEXT NULL,
  `notifDateTime` DATETIME NOT NULL,
  PRIMARY KEY (`idNotification`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`User_has_Notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`User_has_Notification` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`User_has_Notification` (
  `User_userEmail` VARCHAR(100) NOT NULL,
  `Notification_idNotification` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`User_userEmail`, `Notification_idNotification`),
  INDEX `fk_User_has_Notification_Notification1_idx` (`Notification_idNotification` ASC),
  INDEX `fk_User_has_Notification_User1_idx` (`User_userEmail` ASC),
  CONSTRAINT `fk_User_has_Notification_User1`
    FOREIGN KEY (`User_userEmail`)
    REFERENCES `smdedbv1`.`User` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Notification_Notification1`
    FOREIGN KEY (`Notification_idNotification`)
    REFERENCES `smdedbv1`.`Notification` (`idNotification`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`Teacher_has_Subject_has_Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`Teacher_has_Subject_has_Course` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`Teacher_has_Subject_has_Course` (
  `Teacher_idTeacher` VARCHAR(40) NOT NULL,
  `Subject_has_Course_Subject_idSubject` VARCHAR(200) NOT NULL,
  `Subject_has_Course_Course_idCourse` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`Teacher_idTeacher`, `Subject_has_Course_Subject_idSubject`, `Subject_has_Course_Course_idCourse`),
  INDEX `fk_Teacher_has_Subject_has_Course_Subject_has_Course1_idx` (`Subject_has_Course_Subject_idSubject` ASC, `Subject_has_Course_Course_idCourse` ASC),
  INDEX `fk_Teacher_has_Subject_has_Course_Teacher1_idx` (`Teacher_idTeacher` ASC),
  CONSTRAINT `fk_Teacher_has_Subject_has_Course_Teacher1`
    FOREIGN KEY (`Teacher_idTeacher`)
    REFERENCES `smdedbv1`.`Teacher` (`idTeacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teacher_has_Subject_has_Course_Subject_has_Course1`
    FOREIGN KEY (`Subject_has_Course_Subject_idSubject` , `Subject_has_Course_Course_idCourse`)
    REFERENCES `smdedbv1`.`Subject_has_Course` (`Subject_idSubject` , `Course_idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`PublicationAttachedFile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`PublicationAttachedFile` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`PublicationAttachedFile` (
  `idPublicationAttachedFile` VARCHAR(40) NOT NULL,
  `publicationAttachedNameFile` VARCHAR(300) NOT NULL,
  `Publication_idPublication` VARCHAR(40) NOT NULL,
  `fileSize` VARCHAR(20) NULL,
  PRIMARY KEY (`idPublicationAttachedFile`, `Publication_idPublication`),
  INDEX `fk_PublicationAttachedFile_Publication1_idx` (`Publication_idPublication` ASC),
  CONSTRAINT `fk_PublicationAttachedFile_Publication1`
    FOREIGN KEY (`Publication_idPublication`)
    REFERENCES `smdedbv1`.`Publication` (`idPublication`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`FeedbackAttachedFile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`FeedbackAttachedFile` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`FeedbackAttachedFile` (
  `idFeedbackAttachedFile` VARCHAR(40) NOT NULL,
  `feedbackAttachedNameFile` VARCHAR(300) NULL,
  `Feedback_idFeedback` VARCHAR(40) NOT NULL,
  `fileSize` VARCHAR(20) NULL,
  PRIMARY KEY (`idFeedbackAttachedFile`, `Feedback_idFeedback`),
  INDEX `fk_FeedbackAttachedFile_Feedback1_idx` (`Feedback_idFeedback` ASC),
  CONSTRAINT `fk_FeedbackAttachedFile_Feedback1`
    FOREIGN KEY (`Feedback_idFeedback`)
    REFERENCES `smdedbv1`.`Feedback` (`idFeedback`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`User_like_ForumComment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`User_like_ForumComment` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`User_like_ForumComment` (
  `User_userEmail` VARCHAR(100) NOT NULL,
  `ForumComment_idForumComment` VARCHAR(40) NOT NULL,
  `likeStatus` TINYINT(1) NOT NULL,
  PRIMARY KEY (`User_userEmail`, `ForumComment_idForumComment`),
  INDEX `fk_User_has_ForumComment_ForumComment1_idx` (`ForumComment_idForumComment` ASC),
  INDEX `fk_User_has_ForumComment_User1_idx` (`User_userEmail` ASC),
  CONSTRAINT `fk_User_has_ForumComment_User1`
    FOREIGN KEY (`User_userEmail`)
    REFERENCES `smdedbv1`.`User` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_ForumComment_ForumComment1`
    FOREIGN KEY (`ForumComment_idForumComment`)
    REFERENCES `smdedbv1`.`ForumComment` (`idForumComment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`ForumCommentReply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`ForumCommentReply` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`ForumCommentReply` (
  `idForumCommentReply` VARCHAR(40) NOT NULL,
  `forumCommentReplyText` MEDIUMTEXT NOT NULL,
  `forumCommentReplyDateTime` DATETIME NOT NULL,
  `User_userEmail` VARCHAR(100) NOT NULL,
  `ForumComment_idForumComment` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idForumCommentReply`, `User_userEmail`, `ForumComment_idForumComment`),
  INDEX `fk_ForumComment_Reply_User1_idx` (`User_userEmail` ASC),
  INDEX `fk_ForumComment_Reply_ForumComment1_idx` (`ForumComment_idForumComment` ASC),
  CONSTRAINT `fk_ForumComment_Reply_User1`
    FOREIGN KEY (`User_userEmail`)
    REFERENCES `smdedbv1`.`User` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ForumComment_Reply_ForumComment1`
    FOREIGN KEY (`ForumComment_idForumComment`)
    REFERENCES `smdedbv1`.`ForumComment` (`idForumComment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smdedbv1`.`User_like_ForumCommentReply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smdedbv1`.`User_like_ForumCommentReply` ;

CREATE TABLE IF NOT EXISTS `smdedbv1`.`User_like_ForumCommentReply` (
  `User_userEmail` VARCHAR(100) NOT NULL,
  `Reply_idForumCommentReply` VARCHAR(40) NOT NULL,
  `likeStatus` TINYINT(1) NOT NULL,
  PRIMARY KEY (`User_userEmail`, `Reply_idForumCommentReply`),
  INDEX `fk_User_has_ForumComment_Reply_ForumComment_Reply1_idx` (`Reply_idForumCommentReply` ASC),
  INDEX `fk_User_has_ForumComment_Reply_User1_idx` (`User_userEmail` ASC),
  CONSTRAINT `fk_User_has_ForumComment_Reply_User1`
    FOREIGN KEY (`User_userEmail`)
    REFERENCES `smdedbv1`.`User` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_ForumComment_Reply_ForumComment_Reply1`
    FOREIGN KEY (`Reply_idForumCommentReply`)
    REFERENCES `smdedbv1`.`ForumCommentReply` (`idForumCommentReply`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `smdedbv1`.`Institute`
-- -----------------------------------------------------
START TRANSACTION;
USE `smdedbv1`;
INSERT INTO `smdedbv1`.`Institute` (`idInstitute`, `instituteName`) VALUES ('IPNCECyt9JDDB', 'CECyT 9 Juan de Dios Bátiz');

COMMIT;

